
find_library(EDUPALS_N4D_AGENT_LIB "edupals-n4d-agent")
set(EDUPALS_N4D_AGENT_INCLUDE_DIRS "/usr/include/edupals/n4d/")
set(EDUPALS_N4D_AGENT_LIBRARIES ${EDUPALS_N4D_AGENT_LIB})

add_library(Edupals::N4D::Agent SHARED IMPORTED)
set_target_properties(Edupals::N4D::Agent PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${EDUPALS_N4D_AGENT_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES "Edupals::N4D::Agent"
    IMPORTED_LOCATION ${EDUPALS_N4D_AGENT_LIBRARIES}
)
